# Generated by Django 4.0.3 on 2022-03-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_prize',
            field=models.PositiveIntegerField(),
        ),
    ]
