# Generated by Django 4.0.3 on 2022-03-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_product_prize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodect_size',
            new_name='product_size',
        ),
    ]
