# Generated by Django 4.0.3 on 2022-03-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_prodect_size_product_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_prize',
            new_name='product_price',
        ),
    ]
