# Generated by Django 4.0.3 on 2022-03-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_collection',
        ),
        migrations.AddField(
            model_name='product',
            name='product_title',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women'), ('kids', 'kids')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue'), ('white', 'white'), ('black', 'black'), ('yellow', 'yellow'), ('pink', 'pink')], max_length=100),
        ),
    ]
