# Generated by Django 4.0.3 on 2022-03-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_product_product_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_title',
            new_name='product_name',
        ),
    ]
