# Generated by Django 4.0.3 on 2022-04-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='street_address1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address2',
            field=models.CharField(max_length=100),
        ),
    ]
