# Generated by Django 4.0.3 on 2022-04-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
